import fs from "fs";
import path from "path";
import { uniqueFilter } from "./uniqueFilter";
import { SSSX_URLS_INDEX } from "./constants";

const getFullPath = (cwd: string) =>
  path.normalize(`${cwd}/${SSSX_URLS_INDEX}`);

export const loadExistingURLs = async (cwd: string) => {
  let array: string[] = [];
  const fullpath = getFullPath(cwd);
  if (fs.existsSync(fullpath)) {
    const module = await import(fullpath);
    array = [...module.urls].filter(uniqueFilter);
  }

  return array;
};

export const writeURLsIndex = async (cwd: string, urls: string[]) => {
  const fullpath = getFullPath(cwd);
  const array = [...urls, ...(await loadExistingURLs(cwd))]
    .filter(uniqueFilter)
    .sort();

  let data = `// Do not edit! this file was automatically generated by SSSX\n`;
  data += `export const urls = [\n`;
  array.map((url) => {
    data += `"${url}",\n`;
  });
  data += `];\n`;
  fs.writeFileSync(fullpath, data, "utf8");
};
