import fs from "fs";
import path from "path";
import { uniqueFilter } from "./uniqueFilter";

const FILENAME = `sssx.urls.ts`;

export const writeURLsIndex = async (cwd: string, urls: string[]) => {
  let array = urls;
  const fullpath = path.normalize(`${cwd}/${FILENAME}`);
  if (fs.existsSync(fullpath)) {
    const module = await import(fullpath);
    array = [...urls, ...module.urls].filter(uniqueFilter);
  }

  array = array.sort();

  let data = `// do not edit. this file was automatically generated by SSSX\n`;
  data += `export const urls = [\n`;
  array.map((url) => {
    data += `"${url}",\n`;
  });
  data += `];\n`;
  fs.writeFileSync(fullpath, data, "utf8");
};
