import fs from "fs";
import path from "path";
import { uniqueFilter } from "./uniqueFilter";

const FILENAME = `sssx.files.ts`;

// TODO: figure out removal of the files here
export const writeFilesIndex = async (cwd: string, files: string[]) => {
  let array = files;
  const fullpath = path.normalize(`${cwd}/${FILENAME}`);
  if (fs.existsSync(fullpath)) {
    // TODO: read and modify
    const module = await import(fullpath);
    array = [...files, ...module.files].filter(uniqueFilter);
  }

  array = array.sort();

  let data = `// do not edit. this file was automatically generated by SSSX\n`;
  data += `export const files = [\n`;
  array.map((file) => {
    data += `"${file}",\n`;
  });
  data += `];\n`;
  fs.writeFileSync(fullpath, data, "utf8");
};
