import fs from "fs";
import path from "path";

export const writeURLs = async (cwd: string, urls: string[]) => {
  let array = urls;
  const fullpath = path.normalize(`${cwd}/sssx.urls.ts`);
  if (fs.existsSync(fullpath)) {
    // TODO: read and modify
    const module = await import(fullpath);
    array = [...urls, ...module.urls].filter(
      (value, index, array) => array.indexOf(value) === index //filter unique only
    );
  }

  array = array.sort();

  let data = `// do not edit. this file was automatically generated by SSSX\n`;
  data += `export const urls = [\n`;
  array.map((url) => {
    data += `"${url}",\n`;
  });
  data += `];\n`;
  fs.writeFileSync(fullpath, data, "utf8");
};
