import { type Config as InnerConfig } from "./config.ts";

export type Config = Partial<InnerConfig>;
export type { SSSXPlugin, BuildContext, RouteContext } from "./plugins/types.ts";
export type { RouteInfo, RouteModule } from "./routes/types.ts";
export type { SEOMeta } from "./plugins/seo.ts";
export type { ImageConfig } from "./plugins/imageOptimizer.ts";
export { responsiveImage, pictureElement, copyImageHashed } from "./plugins/imageOptimizer.ts";
export { generateSEOHead } from "./plugins/seo.ts";
export { generateJsonLD } from "./plugins/jsonld.ts";
export { buildRSS } from "./plugins/rss.ts";
export type { SSSXTheme } from "./themes/types.ts";
export { loadTheme } from "./themes/types.ts";
export type { ImageMap, ImageEntry } from "./plugins/imagePipeline.ts";
export { processContentImages, resolveContentImage, getImagesForRoute } from "./plugins/imagePipeline.ts";
export type { JsonDataResult } from "./routes/loadJsonData.ts";
export { loadJsonData, mergeJsonData } from "./routes/loadJsonData.ts";
export { DependencyGraph } from "./indexes/dependencyGraph.ts";
export { paginate, taxonomyPages } from "./routes/pagination.ts";
export type { PaginatedPage, PaginationOptions, TaxonomyPage } from "./routes/pagination.ts";
export { rehypeRewriteImages } from "./plugins/rehypeImages.ts";
export { buildSearchIndex } from "./plugins/search.ts";
export type { SearchEntry, SearchIndex } from "./plugins/search.ts";
export { filterContentRoutes } from "./plugins/contentFilters.ts";
export { collectRedirects } from "./plugins/redirects.ts";
export { checkLinks } from "./plugins/linkChecker.ts";
export { compressOutput } from "./plugins/compress.ts";
export { computeDeployDiff } from "./plugins/deployDiff.ts";
export { getVersion } from "./utils/version.ts";
