import fs from "node:fs";
import { type Config } from "../config.ts";
import { generateCSP } from "./csp.ts";

/**
 * Generate _headers file for Netlify/Cloudflare Pages.
 * Includes caching, security headers, and CSP.
 */
export const buildHeaders = (outdir: string, config: Config) => {
  const csp = generateCSP(config);

  const content = `# Generated by SSSX

# Hashed assets — immutable, cache forever
/_assets/*
  Cache-Control: public, max-age=31536000, immutable

# HTML — always revalidate
/*.html
  Cache-Control: no-cache
  X-Content-Type-Options: nosniff
  Content-Security-Policy: ${csp}

# Default security headers
/*
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()
`;

  fs.writeFileSync(`${outdir}/_headers`, content, "utf8");
};

/**
 * Generate _redirects file for Netlify.
 */
export const buildRedirects = (outdir: string, _config: Config) => {
  const filepath = `${outdir}/_redirects`;
  if (!fs.existsSync(filepath)) {
    fs.writeFileSync(filepath, "# Generated by SSSX\n", "utf8");
  }
};
