import fs from "node:fs";
import { type Config } from "../config.ts";

/**
 * Generate _headers file for Netlify/Cloudflare Pages.
 * Sets aggressive caching for hashed assets.
 */
export const buildHeaders = (outdir: string, _config: Config) => {
  const content = `# Generated by SSSX

# Hashed assets — immutable, cache forever
/_assets/*
  Cache-Control: public, max-age=31536000, immutable

# HTML — always revalidate
/*.html
  Cache-Control: no-cache
  X-Content-Type-Options: nosniff

# Default security headers
/*
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  Referrer-Policy: strict-origin-when-cross-origin
`;

  fs.writeFileSync(`${outdir}/_headers`, content, "utf8");
};

/**
 * Generate _redirects file for Netlify.
 * Handles SPA-style fallback to 404.
 */
export const buildRedirects = (outdir: string, _config: Config) => {
  const content = `# Generated by SSSX
# Custom redirects can be added below

`;

  // Only write if it doesn't exist (don't overwrite user's custom redirects)
  const filepath = `${outdir}/_redirects`;
  if (!fs.existsSync(filepath)) {
    fs.writeFileSync(filepath, content, "utf8");
  }
};
