import fs from "node:fs";
import path from "node:path";
import { type Config } from "../config.ts";
import { type RouteInfo } from "../routes/types.ts";

/**
 * Redirect management for large static sites.
 *
 * Sources:
 * 1. Frontmatter `redirect_from` field — old URLs that should redirect here
 * 2. Frontmatter `redirect_to` field — this page redirects elsewhere
 * 3. _redirects.json file in project root
 *
 * Generates:
 * - _redirects file (Netlify format)
 * - HTML meta-refresh redirect pages
 * - Vercel redirects in vercel.json format
 */

export interface Redirect {
  from: string;
  to: string;
  status: number;
}

/**
 * Collect redirects from all routes' frontmatter.
 */
export const collectRedirects = (routes: RouteInfo[], cwd: string): Redirect[] => {
  const redirects: Redirect[] = [];

  for (const route of routes) {
    const p = route.param || {};

    // redirect_from: old URLs that should point to this page
    if (p.redirect_from) {
      const froms = Array.isArray(p.redirect_from)
        ? p.redirect_from
        : [p.redirect_from];
      for (const from of froms) {
        redirects.push({ from: String(from), to: route.permalink, status: 301 });
      }
    }

    // redirect_to: this page redirects elsewhere
    if (p.redirect_to) {
      redirects.push({ from: route.permalink, to: String(p.redirect_to), status: 301 });
    }
  }

  // Load _redirects.json if it exists
  const jsonPath = path.join(cwd, "_redirects.json");
  if (fs.existsSync(jsonPath)) {
    try {
      const custom: Redirect[] = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
      redirects.push(...custom);
    } catch {
      console.warn("Warning: Could not parse _redirects.json");
    }
  }

  return redirects;
};

/**
 * Write _redirects file (Netlify/Cloudflare format)
 */
export const writeRedirectsFile = (outdir: string, redirects: Redirect[]) => {
  if (redirects.length === 0) return;

  const lines = ["# Generated by SSSX", ""];
  for (const r of redirects) {
    lines.push(`${r.from}  ${r.to}  ${r.status}`);
  }

  fs.writeFileSync(path.join(outdir, "_redirects"), lines.join("\n") + "\n", "utf8");
};

/**
 * Generate HTML meta-refresh redirect pages.
 * These work on any static host.
 */
export const writeRedirectPages = (outdir: string, redirects: Redirect[]) => {
  for (const r of redirects) {
    // Only create pages for redirects FROM internal paths
    if (r.from.startsWith("/")) {
      const dir = path.join(outdir, r.from);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      const htmlPath = path.join(dir, "index.html");
      // Don't overwrite real pages
      if (fs.existsSync(htmlPath)) continue;

      const html = `<!doctype html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="refresh" content="0;url=${r.to}" />
  <link rel="canonical" href="${r.to}" />
  <title>Redirecting...</title>
</head>
<body>
  <p>Redirecting to <a href="${r.to}">${r.to}</a>...</p>
</body>
</html>
`;
      fs.writeFileSync(htmlPath, html, "utf8");
    }
  }
};
