import fs from "node:fs";
import { type Config } from "../config.ts";

/**
 * Generate robots.txt with sitemap reference
 */
export const buildRobots = (outdir: string, config: Config) => {
  const sitemapUrl = config.site
    ? `Sitemap: ${config.site}sitemap.xml`
    : "";

  const content = `# Generated by SSSX
User-agent: *
Allow: /

${sitemapUrl}
`.trim() + "\n";

  fs.writeFileSync(`${outdir}/robots.txt`, content, "utf8");
};
