import fs from "node:fs";
import dayjs from "dayjs";
import { type Config } from "../config.ts";
import { type RouteInfo } from "../routes/types.ts";
import { cleanURL } from "../utils/cleanURL.ts";

const BANNER = `<!-- Generated by SSSX -->`;

/**
 * Generate RSS 2.0 feed from content routes.
 */
export const buildRSS = (
  outdir: string,
  config: Config,
  routes: RouteInfo[],
  filename: string = "rss.xml"
) => {
  if (!config.site) return;

  // Filter to content routes with dates (blog-like content)
  const contentRoutes = routes
    .filter((r) => r.type === "content" && r.param?.date)
    .sort((a, b) => {
      const da = String(a.param?.date || "");
      const db = String(b.param?.date || "");
      return db.localeCompare(da); // newest first
    })
    .slice(0, 50); // limit to 50 items

  if (contentRoutes.length === 0) return;

  const now = dayjs().toISOString();
  const site = config.site;

  const items = contentRoutes
    .map((r) => {
      const url = cleanURL(`${site}${r.permalink}`);
      const p = r.param || {};
      return `    <item>
      <title>${escapeXml(p.title || r.permalink)}</title>
      <link>${url}</link>
      <guid>${url}</guid>
      ${p.description ? `<description>${escapeXml(p.description)}</description>` : ""}
      ${p.date ? `<pubDate>${dayjs(p.date).toISOString()}</pubDate>` : ""}
    </item>`;
    })
    .join("\n");

  const rss = `<?xml version="1.0" encoding="UTF-8"?>
${BANNER}
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${escapeXml(config.title || "")}</title>
    <link>${site}</link>
    <description>${escapeXml(config.title || "")} RSS Feed</description>
    <lastBuildDate>${now}</lastBuildDate>
    <atom:link href="${cleanURL(`${site}/${filename}`)}" rel="self" type="application/rss+xml"/>
${items}
  </channel>
</rss>
`;

  fs.writeFileSync(`${outdir}/${filename}`, rss, "utf-8");
};

const escapeXml = (str: string): string => {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
};
